### ISSUE TITLE
External URLs with Button Shortcode

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb_shortcodes#3]
Seems like internal URLs work properly but external or FQDN URLs break the HTML output.  May be an issue of multiple URL filters not working and playing well with each other.

**Comment by brookestevens** [comment]
Fixed by changing the filter process order. Updated config is in the profile at [/config/install/optional/filter.format.wysiwyg.yml](https://github.com/CuBoulder/ucb_2021_profile/blob/main/config/optional/filter.format.wysiwyg.yml)
